events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;

        # Servir el Frontend (Tu indexv2.html)
        location / {
            root /usr/share/nginx/html;
            index indexv2.html;
            try_files $uri $uri/ /indexv2.html;
        }

        # Proxy para Keycloak
        location /auth/ {
            proxy_pass http://keycloak_server:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy para el Microservicio FastAPI
        location /api/ {
            proxy_pass http://user_service:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
